services:
  - type: web
    name: sistema-inventario
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
